export enum ConfigEnum {
  TYPE = 'TYPE',
  HOST = 'HOST',
  PORT = 'PORT',
  USERNAME = 'USERNAME',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  DB_SYNC = 'DB_SYNC',

  JWT_SECRET = 'JWT_SECRET',
}
